hbase single  init
terraform-alicloud-modules/terraform-alicloud-hbase pull request #2
Opened 2020-12-02 03:59 UTC by quanyun-ali

hbase single init

2020-12-03 02:31 UTC, zql-tqy requested changes

2020-12-03 02:31 UTC, zql-tqy commented on examples/hbase-1.1/main.tf
> +
添加一个 profile 变量，并在 provider 中声明变量，另一个 example 也是一样
variable "profile" {
  default = "default"
}

2020-12-03 02:31 UTC, zql-tqy commented on README.md
> +Terraform module which creates a HBase Single Database on Alibaba Cloud.
这个 README 要完善，另外要添加一个 changelog，可以参考下 ons 的 module

2020-12-04 02:08 UTC, zql-tqy requested changes

2020-12-04 02:08 UTC, zql-tqy commented on modules/hbase-1.1/variables.tf
> +  description = "core node disk type. Valid value:cloud_ssd, cloud_efficiency."
这个描述首字母改成大写，枚举值使用 Valid value: 'cloud_ssd',  'cloud_efficiency'.

2020-12-04 09:05 UTC, quanyun-ali commented on CHANGELOG.md
> +- **Added:** `hbase single module` [GH-3](https://github.com/terraform-alicloud-modules/terraform-alicloud-hbase/pull/2)
统一为 GH-2, 
pull/1 弃用了

2020-12-04 09:09 UTC, quanyun-ali commented on README.md
> +
已补充

2020-12-04 09:10 UTC, quanyun-ali commented on README-CN.md
> +[English](https://github.com/terraform-alicloud-modules/terraform-alicloud-hbase/blob/master/README.md) | 简体中文
fix

2020-12-04 09:12 UTC, quanyun-ali commented on README-CN.md
> +  source               = "terraform-alicloud-modules/hbase/alicloud/"
add

2020-12-04 09:13 UTC, quanyun-ali commented on examples/hbase-2.0/main.tf
> +  core_disk_size         = 400
fix

2020-12-04 09:21 UTC, quanyun-ali commented on modules/hbase-1.1/variables.tf
> +  description = "core node disk type. Valid value:cloud_ssd, cloud_efficiency."
fix

2020-12-04 09:21 UTC, quanyun-ali commented on main.tf
> +  core_instance_quantity = 1
单机版， 为固定值， 无需开放 var

2020-12-08 04:54 UTC, xiaozhu36 approved these changes

2020-12-08 04:54 UTC, merged